# -*- mode: python ; coding: utf-8 -*-


a = Analysis(
    ['launcher.py'],
    pathex=[],
    binaries=[],
    datas=[('static', 'static'), ('scripts', 'scripts'), ('mcp_servers', 'mcp_servers'), ('services/hwfit/data', 'services/hwfit/data'), ('config', 'config'), ('.env.example', '.env.example')],
    hiddenimports=[
        'gui',
        'gui.app',
        'gui.api',
        'gui.backend',
        'gui.theme',
        'gui.markdown_html',
        'gui.logbus',
        'gui.workers',
        'gui.shell',
        'gui.widgets',
        'gui.widgets.toast',
        'gui.widgets.dialogs',
        'gui.widgets.transcript',
        'gui.widgets.composer',
        'gui.widgets.session_list',
        'gui.views',
        'gui.views.chat',
        'gui.views.documents',
        'gui.views.notes',
        'gui.views.tasks',
        'gui.views.calendar',
        'gui.views.email',
        'gui.views.gallery',
        'gui.views.research',
        'gui.views.models',
        'gui.views.localmodels',
        'gui.views.memory',
        'gui.views.skills',
        'gui.views.mcp',
        'gui.views.settings',
        'gui.views.logs',
        'gui.views.login',
        'gui.views.base',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    noarchive=False,
    optimize=0,
)
pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name='psd.ai',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon=['static\\icon.ico'],
)
coll = COLLECT(
    exe,
    a.binaries,
    a.datas,
    strip=False,
    upx=True,
    upx_exclude=[],
    name='psd.ai',
)
